name: dask-tutorial-hpc
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - xarray
  - zarr
  - graphviz
  - pip
  - pip:
      - aiohttp
      - aiosignal
      - anyio
      - argon2-cffi
      - argon2-cffi-bindings
      - arrow
      - asttokens
      - async-lru
      - async-timeout
      - attrs
      - Babel
      - backcall
      - beautifulsoup4
      - bleach
      - bokeh
      - certifi
      - cffi
      - charset-normalizer
      - click
      - cloudpickle
      - comm
      - contourpy
      - dask
      - dask-labextension
      - debugpy
      - decorator
      - defusedxml
      - distributed
      - exceptiongroup
      - executing
      - fastjsonschema
      - fqdn
      - frozenlist
      - fsspec
      - graphviz
      - idna
      - importlib-metadata
      - ipycytoscape
      - ipykernel
      - ipython
      - ipywidgets
      - isoduration
      - jedi
      - Jinja2
      - json5
      - jsonpointer
      - jsonschema
      - jupyter-events
      - jupyter-lsp
      - jupyter_client
      - jupyter_core
      - jupyter_server
      - jupyter_server_proxy
      - jupyter_server_terminals
      - jupyterlab
      - jupyterlab-pygments
      - jupyterlab-widgets
      - jupyterlab_server
      - locket
      - lz4
      - MarkupSafe
      - matplotlib-inline
      - memory-profiler
      - mistune
      - msgpack
      - multidict
      - nbclient
      - nbconvert
      - nbformat
      - nest-asyncio
      - notebook_shim
      - numpy
      - overrides
      - packaging
      - pandas
      - pandocfilters
      - parso
      - partd
      - pexpect
      - pickleshare
      - Pillow
      - platformdirs
      - prometheus-client
      - prompt-toolkit
      - psutil
      - ptyprocess
      - pure-eval
      - pyarrow
      - pycparser
      - Pygments
      - pyrsistent
      - python-dateutil
      - python-json-logger
      - pytz
      - PyYAML
      - pyzmq
      - requests
      - rfc3339-validator
      - rfc3986-validator
      - Send2Trash
      - simpervisor
      - six
      - sniffio
      - sortedcontainers
      - soupsieve
      - spectate
      - stack-data
      - tblib
      - terminado
      - tinycss2
      - tomli
      - toolz
      - tornado
      - traitlets
      - typing_extensions
      - tzdata
      - uri-template
      - urllib3
      - wcwidth
      - webcolors
      - webencodings
      - websocket-client
      - widgetsnbextension
      - xyzservices
      - yarl
      - zict
      - zipp

